//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class edlines {
  public static int EdgeDrawingLineDetector(SWIGTYPE_p_unsigned_char src, int w, int h, float scaleX, float scaleY, boundingbox_t bbox, List_line_float_t lines) {
    int ret = edlinesPINVOKE.EdgeDrawingLineDetector(SWIGTYPE_p_unsigned_char.getCPtr(src), w, h, scaleX, scaleY, boundingbox_t.getCPtr(bbox), List_line_float_t.getCPtr(lines));
    if (edlinesPINVOKE.SWIGPendingException.Pending) throw edlinesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
