//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class line_float_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public line_float_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(line_float_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~line_float_t() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          edlinesPINVOKE.delete_line_float_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public float startx {
    set {
      edlinesPINVOKE.line_float_t_startx_set(swigCPtr, value);
    } 
    get {
      float ret = edlinesPINVOKE.line_float_t_startx_get(swigCPtr);
      return ret;
    } 
  }

  public float starty {
    set {
      edlinesPINVOKE.line_float_t_starty_set(swigCPtr, value);
    } 
    get {
      float ret = edlinesPINVOKE.line_float_t_starty_get(swigCPtr);
      return ret;
    } 
  }

  public float endx {
    set {
      edlinesPINVOKE.line_float_t_endx_set(swigCPtr, value);
    } 
    get {
      float ret = edlinesPINVOKE.line_float_t_endx_get(swigCPtr);
      return ret;
    } 
  }

  public float endy {
    set {
      edlinesPINVOKE.line_float_t_endy_set(swigCPtr, value);
    } 
    get {
      float ret = edlinesPINVOKE.line_float_t_endy_get(swigCPtr);
      return ret;
    } 
  }

  public line_float_t() : this(edlinesPINVOKE.new_line_float_t(), true) {
  }

}
